<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">


# Telecomm EDA Challenge Lab

_Author: Alex Combs (NYC) _

---

Let's do some Exploratory Data Analysis (EDA)! As a data scientist, you often may find yourself given a data set you've never seen before, and asked to do a rapid analysis. This is today's goal.

# Prompt

You work for a telecommunications company. The company has been storing metadata about customer phone usage, as part of the regular course of business. Currently, this data is sitting in an unsecured database. The company doesn't want to pay to increase their database security, because they don't think there's really anything to be learned from the metadata.

They are under pressure from "right to privacy" organizations to beef up the database security. These organizations argue that you can learn a lot about a person from their cell phone metadata.

The telecom company wants to understand if this is true, and they want your help. They will give you one person's metadata for 2014 and want to see what you can learn from it.

Working in teams, create a report revealing everything you can about the person. Prepare a presentation, with slides, showcasing your findings.


# The Data

The [person's metadata](./datasets/metadata.csv) has the following fields:

| Field Name          | Description
| ---                 | ---
| **Cell Cgi**        | cell phone tower identifier
| **Cell Tower**      | cell phone tower location
| **Comm Identifier** |	de-identified recipient of communication
| **Comm Timedate String** | time of communication
| **Comm Type	Id**  | type of communication
| **Latitude**        | latitude of communication
| **Longitude**       | longitude of communication

# Hints

This is totally open-ended! If you're totally stumped -- and only if stumped -- should you look below for prompts. As a starting point, given that you have geo-locations, consider investigating ways to display this type of information (i.e. mapping functionality).

<font color='white'>
Well for starters, he's in Australia!

Ideas for things to look into:
- where does he work?
- where does he live?
- who does he contact most often?
- what hours does he work?
- did he move?
- did he go on holiday?  If so, where did he go?
- did he get a new phone?

Challenges:
- how does he get to work?
- where does his family live?
- if he went on holiday, can you find which flights he took?
- can you guess who some of his contacts are, based on the frequency, location, time and mode (phone/text) of communications?


If you're stuck on how to map the data, you can try "basemap" or "gmplot", or anything else you find online.
</font>

I belive that you could pull a concerning amount of information from this small dataset. I was able to find their most common location. Additionally I was able to track their location by day via their cell signal. This could potentially lead to finding movement habits/patterns. Where they most commonly use their phone during weekdays between the hours of 6:00PM and 8:00AM is most likely their home address.

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

%matplotlib inline

meta_csv = './datasets/metadata.csv'
df = pd.read_csv(meta_csv)

In [3]:
df.head()

,Cell Cgi,Cell Tower Location,Comm Identifier,Comm Timedate String,Comm Type,Latitude,Longitude
0,50501015388B9,REDFERN TE,f1a6836c0b7a3415a19a90fdd6f0ae18484d6d1e,4/1/14 9:40,Phone,-33.892933,151.202296
1,50501015388B9,REDFERN TE,62157ccf2910019ffd915b11fa037243b75c1624,4/1/14 9:42,Phone,-33.892933,151.202296
2,505010153111F,HAYMARKET #,c8f92bd0f4e6fb45ed7fce96fc831b283db2b642,4/1/14 13:13,Phone,-33.880329,151.205690
3,505010153111F,HAYMARKET #,f1a6836c0b7a3415a19a90fdd6f0ae18484d6d1e,4/1/14 13:13,Phone,-33.880329,151.205690
4,5.05E+106,HAYMARKET #,f1a6836c0b7a3415a19a90fdd6f0ae18484d6d1e,4/1/14 17:27,Phone,-33.880329,151.205690

In [8]:
df.describe()

           Latitude     Longitude
count  10476.000000  10476.000000
mean     -35.136188    150.612841
std        3.141723      1.470169
min      -42.884810    144.848243
25%      -33.884603    151.202296
50%      -33.796610    151.266540
75%      -33.788150    151.266540
max      -33.557310    151.289340

In [12]:
#Possible home address Long - Lat:
print(df['Latitude'].max(), ',', df['Longitude'].max(), ',', df['Cell Tower Location'].max())

-33.55731 , 151.28933999999998 , ZETLAND 757 ELIZABETH ST

In [25]:
df.groupby('Comm Type').max()

,Cell Cgi,Cell Tower Location,Comm Identifier,Comm Timedate String,Latitude,Longitude
Comm Type,,,,,,
Internet,50501E05043CA,ZETLAND 757 ELIZABETH ST,NaN,9/30/14 9:36,-33.57839,151.28934
Phone,50501E0505629,ZETLAND 757 ELIZABETH ST,fdd607340fe1953e0309b180ce432fbcd0c55d46,9/8/14 8:17,-33.75949,151.28934
SMS,50501E0503462,WAHROONGA #,e16514aa8bdc83ba0976bca8a1dc20c9b391dbe6,9/8/14 0:07,-33.55731,151.28934

In [48]:
df.groupby('Cell Tower Location').max()

,Cell Cgi,Comm Timedate String,Comm Type,Latitude,Longitude,Date_Comm,Time_Comm
Cell Tower Location,,,,,,,
71 MACQUARIE ST,5050120033D17,7/27/14 12:30,SMS,-33.861130,151.212930,7/27/14,9:44
AIRPORT LINK,5.05E+12,3/3/15 8:18,Phone,-33.923217,151.187345,3/3/15,8:18
ASCOT VALE SOUTH,50501225008C3,8/30/14 10:59,Phone,-37.777800,144.930000,8/30/14,10:59
BALGOWLAH HAYES ST,505012056EF02,9/30/14 1:37,SMS,-33.788150,151.266540,9/30/14,9:59
BALGOWLAH TE,505012056F102,9/30/14 19:22,SMS,-33.793450,151.263100,9/30/14,9:51
BALGOWLAH VILLAGE SHOPPING CENTRE IBC,5.05E+12,9/30/14 19:33,SMS,-33.793648,151.263934,9/30/14,9:01
BEECHWORTH,50501E0505629,3/29/15 14:06,Phone,-36.356700,146.713600,3/29/15,21:13
BENALLA EAST,50501E05043CA,3/28/15 9:17,Phone,-36.502180,146.111770,3/28/15,9:17
BEROWRA WINDY BANKS INTERCHANGE,5.05E+12,1/24/15 12:25,SMS,-33.635990,151.146900,1/24/15,12:25
BRICKWORKS,5050129505A15,8/11/14 18:30,SMS,-42.859840,147.292150,8/11/14,9:46
BROADWAY OTC,50501200E5E01,8/20/14 17:47,SMS,-33.884603,151.195643,8/20/14,21:24
BROOKLYN PACIFIC HWY,50501B1506465,1/24/15 12:30,SMS,-33.557310,151.193530,1/24/15,12:30
CARLTON COLLEGE SQ,50501225040AA,8/30/14 14:22,Phone,-37.792900,144.968730,8/30/14,14:22
CENTRAL SRA DONOR,505010153A565,9/5/14 13:46,SMS,-33.880240,151.205690,9/5/14,9:52
CHINATOWN,505010153744F,9/25/14 11:45,SMS,-33.878290,151.203450,9/25/14,9:58
CHIPPENDALE,50501200D9E01,9/5/14 13:44,SMS,-33.884171,151.202350,9/5/14,9:59
COLLINS ST (HOBART),5050129503D8A,8/11/14 13:34,Phone,-42.881940,147.328930,8/11/14,17:45
COWAN 1051 PACIFIC HWY,5.05E+12,1/24/15 19:49,SMS,-33.603800,151.163900,1/24/15,19:49
COWAN LOT 1,50501B1500B24,1/24/15 12:28,SMS,-33.578390,151.184450,1/24/15,12:28
CREMORNE #,50501200A6A03,7/27/14 20:18,SMS,-33.830960,151.225490,7/27/14,9:21
CREMORNE JUNCTION; GERARD ST,505010152532C,9/20/14 16:49,Phone,-33.828073,151.226275,9/20/14,9:14
DALLEY2 #,5050101536BB7,2/4/15 17:29,Phone,-33.862850,151.208430,2/4/15,17:29
DARLINGHURST,50501202B6D03,8/21/14 18:09,SMS,-33.878140,151.213600,8/21/14,20:05
DAVID JONES,5050101533FF5,7/11/14 13:10,Phone,-33.870300,151.210100,7/11/14,13:10
DEE WHY,50501015241A6,3/4/15 13:43,Phone,-33.759490,151.281350,3/4/15,13:43
EDGECLIFF EXCHANGE (PO),5050101530DB8,5/10/14 14:15,Phone,-33.879320,151.238020,5/10/14,14:15
FAIRLIGHT 137 SYDNEY RD,50501015325CB,9/27/14 18:52,SMS,-33.796610,151.277560,9/27/14,9:30
GRAND CHANCELLOR 1800,5.05E+12,8/12/14 11:59,Phone,-42.881010,147.333460,8/12/14,11:59
HARBORD 22 WAINE ST,5.05E+12,9/29/14 21:23,SMS,-33.779333,151.276901,9/29/14,9:57
HAYMARKET #,505010153136E,9/7/14 20:41,SMS,-33.880329,151.205690,9/7/14,9:59
...,...,...,...,...,...,...,...
MASCOT INTERNATIONAL AIRPORT TERMINAL T1,50501015223F4,3/3/15 8:06,Phone,-33.937558,151.165700,3/3/15,9:59
MASCOT M5 MOTORWAY EMERGENCY STAIRS,5.05E+12,10/18/14 11:30,SMS,-33.946740,151.167140,10/18/14,15:46
MELB AIRPORT TERM,5050122513CAB,8/30/14 10:32,Phone,-37.670418,144.848243,8/30/14,10:32
MOUNT RUMNEY,5.05E+12,5/4/14 20:51,Phone,-42.860600,147.454200,5/4/14,20:51
NEUTRAL BAY MILITARYRD,50501200A3B04,2/6/15 20:23,SMS,-33.829400,151.218280,2/6/15,8:59
NEW TOWN,505012950027A,8/12/14 11:55,SMS,-42.853070,147.315320,8/12/14,9:36
NEWTOWN TE,505010152762F,5/24/14 18:25,SMS,-33.896050,151.179640,5/24/14,18:25
NORTH HOBART 1800,5.05E+12,12/24/14 11:31,Phone,-42.874570,147.317880,12/24/14,18:00
NORTH SYDNEY 54 MCLAREN,5050101531BE0,3/17/15 6:31,Phone,-33.834150,151.208890,3/17/15,6:31
POLICE HEADQUARTERS,5.05E+12,11/14/14 17:44,Phone,-42.880290,147.328080,11/14/14,17:44
REDFERN TE,5050120576C03,9/8/14 8:17,SMS,-33.892933,151.202296,9/8/14,9:55
REDFERN; 495 CLEVELAND ST,5050101534F1B,6/1/14 12:02,Phone,-33.892330,151.216530,6/1/14,12:02
ROSEBERY DUNNING AVE,5050101521FA0,3/7/15 10:25,Phone,-33.911320,151.203950,3/7/15,10:25
SEAFORTH,50501015220A3,3/24/15 18:34,Phone,-33.792750,151.241250,3/24/15,6:17
SPIT BRIDGE,505012056A101,9/29/14 6:20,SMS,-33.806380,151.246980,9/29/14,9:53
SUNDERLAND ST,5050140014D01,8/11/14 9:16,SMS,-42.843380,147.295690,8/11/14,9:57
SURRY HILLS,505010153226D,6/1/14 11:56,SMS,-33.889640,151.211420,6/1/14,9:49
SURRY HILLS 418A ELIZABETH ST,505010153424F,9/19/14 10:04,SMS,-33.886400,151.208800,9/19/14,9:56
SYDNEY 131 YORK ST,50501015322ED,7/23/14 11:33,Phone,-33.872150,151.206140,7/23/14,13:28
SYDNEY 2 CASTLEREAGH STREET,5050101538CDF,5/8/14 21:05,SMS,-33.866550,151.210330,5/8/14,21:05
SYDNEY 450 GEORGE ST,5050101536A3B,6/21/14 15:20,SMS,-33.870550,151.207930,6/21/14,15:20
SYDNEY 505 GEORGE ST,5.05E+12,9/29/14 9:32,Phone,-33.875130,151.205840,9/29/14,9:32
SYDNEY DOMESTIC TERMINAL T2 - VIRGIN,5050101528CFE,8/9/14 9:46,Phone,-33.934160,151.179380,8/9/14,9:46
SYDNEY INTERNATIONAL AIRPORT RAILWAY STN,5050101529AF9,3/3/15 8:08,Phone,-33.934674,151.164520,3/3/15,8:08
THE ROCKS 55 HARRINGTON ST,5.05E+12,2/3/15 21:06,Phone,-33.859470,151.207490,2/3/15,9:21
THOONA,50501E0503462,3/28/15 11:55,SMS,-36.331075,146.075432,3/28/15,20:11
ULTIMO BULWARA RD,50501015325CC,9/21/14 15:46,Phone,-33.879000,151.198010,9/21/14,5:13
ULTIMO; 616-620 HARRIS ST,505010153A55F,3/31/15 17:14,Phone,-33.880580,151.200460,3/31/15,9:46
WAHROONGA #,5.05E+12,1/24/15 12:11,SMS,-33.717630,151.116580,1/24/15,12:11
ZETLAND 757 ELIZABETH ST,5.05E+12,3/14/15 11:38,Phone,-33.905330,151.205781,3/14/15,12:12

In [64]:
import datetime
new = df['Comm Timedate String'].str.split(' ', n=1, expand = True)
df['Date_Comm'] = new[0]
df['Time_Comm'] = new[1]


df

,Cell Cgi,Cell Tower Location,Comm Identifier,Comm Timedate String,Comm Type,Latitude,Longitude,Date_Comm,Time_Comm
0,50501015388B9,REDFERN TE,f1a6836c0b7a3415a19a90fdd6f0ae18484d6d1e,4/1/14 9:40,Phone,-33.892933,151.202296,4/1/14,9:40
1,50501015388B9,REDFERN TE,62157ccf2910019ffd915b11fa037243b75c1624,4/1/14 9:42,Phone,-33.892933,151.202296,4/1/14,9:42
2,505010153111F,HAYMARKET #,c8f92bd0f4e6fb45ed7fce96fc831b283db2b642,4/1/14 13:13,Phone,-33.880329,151.205690,4/1/14,13:13
3,505010153111F,HAYMARKET #,f1a6836c0b7a3415a19a90fdd6f0ae18484d6d1e,4/1/14 13:13,Phone,-33.880329,151.205690,4/1/14,13:13
4,5.05E+106,HAYMARKET #,f1a6836c0b7a3415a19a90fdd6f0ae18484d6d1e,4/1/14 17:27,Phone,-33.880329,151.205690,4/1/14,17:27
5,5050101532B23,CHIPPENDALE,6bbc17070aa91e2dab7909b96c6eecbd6109ba56,4/1/14 17:36,Phone,-33.884171,151.202350,4/1/14,17:36
6,5050101536E5E,CHIPPENDALE,6bbc17070aa91e2dab7909b96c6eecbd6109ba56,4/1/14 17:40,Phone,-33.884171,151.202350,4/1/14,17:40
7,5050101531F08,REDFERN TE,7cb96eadd3ff95e25406d24794027c443c0661c5,4/2/14 19:18,Phone,-33.892933,151.202296,4/2/14,19:18
8,505010153111F,HAYMARKET #,de40c5c1f9249f95f7fb216931db58747afef74f,4/3/14 14:35,Phone,-33.880329,151.205690,4/3/14,14:35
9,505010153111F,HAYMARKET #,66f32c1163d0e597983b65c51f5a477070ad3785,4/3/14 14:36,Phone,-33.880329,151.205690,4/3/14,14:36
10,50501015388BC,REDFERN TE,bc0b01860486b0f0a240ce8419d3d7553fe404ab,4/4/14 9:12,SMS,-33.892933,151.202296,4/4/14,9:12
11,50501015388BC,REDFERN TE,62157ccf2910019ffd915b11fa037243b75c1624,4/4/14 9:39,Phone,-33.892933,151.202296,4/4/14,9:39
12,50501015388BC,REDFERN TE,91aba4a11359ff3af7902428d20cfa7e676c36e7,4/4/14 9:39,Phone,-33.892933,151.202296,4/4/14,9:39
13,5050101537A4A,CHIPPENDALE,91aba4a11359ff3af7902428d20cfa7e676c36e7,4/4/14 9:47,Phone,-33.884171,151.202350,4/4/14,9:47
14,505010153111F,HAYMARKET #,de40c5c1f9249f95f7fb216931db58747afef74f,4/4/14 14:00,Phone,-33.880329,151.205690,4/4/14,14:00
15,5.05E+106,HAYMARKET #,de40c5c1f9249f95f7fb216931db58747afef74f,4/4/14 15:11,Phone,-33.880329,151.205690,4/4/14,15:11
16,505010153111F,HAYMARKET #,b5238f237b241802d59fce177e4f9f016ae3d4f6,4/4/14 15:20,Phone,-33.880329,151.205690,4/4/14,15:20
17,5050101536E5E,CHIPPENDALE,91aba4a11359ff3af7902428d20cfa7e676c36e7,4/4/14 18:10,Phone,-33.884171,151.202350,4/4/14,18:10
18,505010153A14C,HAYMARKET TE LEVEL 5 SRA BTS HOTEL,91aba4a11359ff3af7902428d20cfa7e676c36e7,4/4/14 18:28,Phone,-33.880240,151.205690,4/4/14,18:28
19,50501015369CB,71 MACQUARIE ST,91aba4a11359ff3af7902428d20cfa7e676c36e7,4/4/14 18:31,Phone,-33.861130,151.212930,4/4/14,18:31
20,505010152532C,FAIRLIGHT 137 SYDNEY RD,c8f92bd0f4e6fb45ed7fce96fc831b283db2b642,4/4/14 18:57,Phone,-33.796610,151.277560,4/4/14,18:57
21,505010152532C,FAIRLIGHT 137 SYDNEY RD,91aba4a11359ff3af7902428d20cfa7e676c36e7,4/4/14 18:58,Phone,-33.796610,151.277560,4/4/14,18:58
22,5.05E+12,MANLY #,dc6774d10eeca42629f043d3649f1edf903b0dab,4/5/14 15:10,Phone,-33.796679,151.285293,4/5/14,15:10
23,5050101531F08,REDFERN TE,62157ccf2910019ffd915b11fa037243b75c1624,4/7/14 10:46,Phone,-33.892933,151.202296,4/7/14,10:46
24,50501015388BC,REDFERN TE,bc0b01860486b0f0a240ce8419d3d7553fe404ab,4/7/14 12:31,SMS,-33.892933,151.202296,4/7/14,12:31
25,50501015388BC,REDFERN TE,70e1f163d854d4e9b63e9a3f4056ced467567d85,4/7/14 18:18,SMS,-33.892933,151.202296,4/7/14,18:18
26,5050101531F05,REDFERN TE,12e3d1b0c95aa32b6890c4455918dfc10e09fb51,4/7/14 18:23,Phone,-33.892933,151.202296,4/7/14,18:23
27,5050101531F05,REDFERN TE,6bbc17070aa91e2dab7909b96c6eecbd6109ba56,4/7/14 18:31,Phone,-33.892933,151.202296,4/7/14,18:31
28,5050101531F08,REDFERN TE,70e1f163d854d4e9b63e9a3f4056ced467567d85,4/7/14 18:39,SMS,-33.892933,151.202296,4/7/14,18:39
29,5050101531F08,REDFERN TE,70e1f163d854d4e9b63e9a3f4056ced467567d85,4/7/14 18:39,SMS,-33.892933,151.202296,4/7/14,18:39
...,...,...,...,...,...,...,...,...,...
10446,5050101531F05,REDFERN TE,c13b4711ebc07ab70537d8d6f6326edb1c7b419a,4/1/15 19:00,Phone,-33.892933,151.202296,4/1/15,19:00
10447,50501015388B9,REDFERN TE,NaN,4/1/15 19:07,Internet,-33.892933,151.202296,4/1/15,19:07
10448,50501015388B9,REDFERN TE,NaN,4/1/15 19:09,Internet,-33.892933,151.202296,4/1/15,19:09
10449,50501015388B9,REDFERN TE,NaN,4/1/15 19:09,Internet,-33.892933,151.202296,4/1/15,19:09
10450,50501015388B9,REDFERN TE,NaN,4/1/15 19:09,Internet,-33.892933,151.202296,4/1/15,19:09
10451,50501015388B9,REDFERN TE,NaN,4/1/15 19:20,Internet,-33.892933,151.202296,4/1/15,19:20
10452,50501015388B9,REDFERN TE,NaN,4/1/15 19:20,Internet,-33.892933,151.202296,4/1/15,19:20
10453,50501015388B9,REDFERN TE,NaN,4/1/15 19:25,Internet,-33.892933,151.202296,4/1/15,19:25
10454,50501015388B9,REDFERN TE,NaN,4/1/15 19:58,Internet,-33.892933,151.202296,4/1/15,19:58
10455,50501015388B9,REDFERN TE,NaN,4/1/15 20:13,Internet,-33.892933,151.202296,4/1/15,20:13
10456,50501015388B9,REDFERN TE,NaN,4/1/15 20:13,Internet,-33.892933,151.202296,4/1/15,20:13
10457,50501015388B9,REDFERN TE,NaN,4/1/15 20:15,Internet,-33.892933,151.202296,4/1/15,20:15
10458,50501015388B9,REDFERN TE,NaN,4/1/15 20:15,Internet,-33.892933,151.202296,4/1/15,20:15
10459,50501015388B9,REDFERN TE,NaN,4/1/15 20:16,Internet,-33.892933,151.202296,4/1/15,20:16
10460,5050101531F05,REDFERN TE,91aba4a11359ff3af7902428d20cfa7e676c36e7,4/1/15 20:16,Phone,-33.892933,151.202296,4/1/15,20:16
10461,50501015388B9,REDFERN TE,NaN,4/1/15 20:49,Internet,-33.892933,151.202296,4/1/15,20:49
10462,50501015388B9,REDFERN TE,NaN,4/1/15 20:49,Internet,-33.892933,151.202296,4/1/15,20:49
10463,50501015388B9,REDFERN TE,NaN,4/1/15 20:50,Internet,-33.892933,151.202296,4/1/15,20:50
10464,50501015388B9,REDFERN TE,NaN,4/1/15 21:03,Internet,-33.892933,151.202296,4/1/15,21:03
10465,50501015388B9,REDFERN TE,NaN,4/1/15 21:03,Internet,-33.892933,151.202296,4/1/15,21:03
10466,5050101531F05,REDFERN TE,91aba4a11359ff3af7902428d20cfa7e676c36e7,4/1/15 21:03,Phone,-33.892933,151.202296,4/1/15,21:03
10467,50501015388B9,REDFERN TE,NaN,4/1/15 21:04,Internet,-33.892933,151.202296,4/1/15,21:04
10468,50501015388B9,REDFERN TE,NaN,4/1/15 21:20,Internet,-33.892933,151.202296,4/1/15,21:20
10469,50501015388B9,REDFERN TE,NaN,4/1/15 21:20,Internet,-33.892933,151.202296,4/1/15,21:20
10470,50501015388B9,REDFERN TE,NaN,4/1/15 21:32,Internet,-33.892933,151.202296,4/1/15,21:32
10471,50501015388B9,REDFERN TE,NaN,4/1/15 22:40,Internet,-33.892933,151.202296,4/1/15,22:40
10472,50501015388B9,REDFERN TE,NaN,4/1/15 22:41,Internet,-33.892933,151.202296,4/1/15,22:41
10473,50501015388B9,REDFERN TE,NaN,4/1/15 22:44,Internet,-33.892933,151.202296,4/1/15,22:44
10474,50501015388B9,REDFERN TE,NaN,4/1/15 22:45,Internet,-33.892933,151.202296,4/1/15,22:45
10475,50501015388B9,REDFERN TE,NaN,4/1/15 23:49,Internet,-33.892933,151.202296,4/1/15,23:49

In [60]:
#This can describe the users movement based off of Lat-Long
df.groupby(['Date_Comm', 'Time_Comm']).mean()

                      Latitude   Longitude
Date_Comm Time_Comm
1/1/15    0:19      -33.788150  151.266540
          0:20      -33.788150  151.266540
          10:01     -33.779333  151.276901
          10:03     -33.779333  151.276901
          10:04     -33.783742  151.271721
          10:06     -33.788150  151.266540
          10:08     -33.788150  151.266540
          10:14     -33.788150  151.266540
          10:16     -33.788150  151.266540
          10:19     -33.788150  151.266540
          10:21     -33.788150  151.266540
          10:24     -33.788150  151.266540
          10:27     -33.788150  151.266540
          10:29     -33.788150  151.266540
          10:34     -33.788150  151.266540
          10:37     -33.788150  151.266540
          10:39     -33.788150  151.266540
          10:42     -33.788150  151.266540
          10:49     -33.788150  151.266540
          11:02     -33.788150  151.266540
          11:03     -33.788150  151.266540
          15:24     -33.788150  151.266540
          15:59     -33.788150  151.266540
          17:04     -33.788150  151.266540
          18:05     -33.788150  151.266540
          19:13     -33.788150  151.266540
          19:34     -33.788150  151.266540
          19:35     -33.788150  151.266540
          1:11      -33.788150  151.266540
          1:37      -33.788150  151.266540
...                        ...         ...
9/29/14   21:23     -33.785946  151.269130
          21:25     -33.788150  151.266540
          21:27     -33.788150  151.266540
          6:20      -33.806380  151.246980
          9:32      -33.876863  151.205790
          9:45      -33.880329  151.205690
9/3/14    15:43     -33.892933  151.202296
9/30/14   19:01     -33.884171  151.202350
          19:03     -33.884171  151.202350
          19:22     -33.793450  151.263100
          19:33     -33.793648  151.263934
          19:52     -33.788150  151.266540
          1:37      -33.788150  151.266540
          9:36      -33.884171  151.202350
9/4/14    16:52     -33.892933  151.202296
          17:19     -33.892933  151.202296
          17:38     -33.892933  151.202296
          18:37     -33.892933  151.202296
9/5/14    11:04     -33.892933  151.202296
          13:18     -33.884171  151.202350
          13:44     -33.884171  151.202350
          13:46     -33.880240  151.205690
          16:41     -33.892933  151.202296
          16:42     -33.892933  151.202296
9/6/14    20:05     -33.796679  151.285293
9/7/14    20:41     -33.880329  151.205690
9/8/14    0:07      -33.892933  151.202296
          16:26     -33.892933  151.202296
          8:16      -33.892933  151.202296
          8:17      -33.892933  151.202296

[6382 rows x 2 columns]